llm: "Jackrong:MLX-Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled-bf16"
model_url: "http://localhost:1234/v1"
api_key: "no_need"

analysis_llm: "Jackrong:MLX-Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled-bf16"
analysis_model_url: "http://localhost:1234/v1"
analysis_api_key: "no_need"

simulation_llm: "Jackrong:MLX-Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled-bf16"
simulation_model_url: "http://localhost:1234/v1"
simulation_api_key: "no_need"

mcp:
  ip: "http://localhost"
  port: "18001"
