llm:
  chat: 'republicofkorokke-qwen3.5-4b-mlx-lm'
  analysis: 'republicofkorokke-qwen3.5-4b-mlx-lm'
  simulation: 'republicofkorokke-qwen3.5-4b-mlx-lm'
  summary: 'qwen3-1.7b-mlx'
  tool_selector: 'qwen3-0.6b-mlx'
  judge: 'republicofkorokke-qwen3.5-4b-mlx-lm'

model_url: "http://localhost:1234/v1"

mcp:
  ip: "http://localhost"
  port: "8001"